tasks:
  - init: ./.init-workspace.sh && exit

  # Ref: https://github.com/gitpod-io/gitpod/issues/1997
  - name: pre-commit workaround
    command: echo "export PIP_USER=false" >> ~/.bashrc && . ~/.bashrc && exit

  - name: personalize terminal
    command: cat .personal.bashrc >> ~/.bashrc && . ~/.bashrc && exit
